### ISSUE TITLE
Out of Date RapidJSON dependency causing compile failure

### ISSUE THREAD

**Issue by juniperfdel** [cern-fts/davix#120]
The RapidJSON dependency in the source tree is out of date and the following issue is preventing compilation using new compilers.

https://github.com/Tencent/rapidjson/issues/2277

**Comment by mpatrascoiu** [comment]
Hello,

The merge request https://github.com/cern-fts/davix/pull/119 should address this.
Will be released in Davix v0.8.7.

Cheers,
Mihai

**Comment by mpatrascoiu** [comment]
Hello,

In fact, I was wrong and the merge request #119 did not in fact address this issue.
The issue was reported again in #130 (previously to that, a fix was submitted in #129).

By now, #129 was merged and the situation should be addressed.

I'm also tracking this issue internally:
- [DMC-1426](https://its.cern.ch/jira/browse/DMC-1426): Remove dependency on RapidJSON from the Davix codebase
- [DMC-1427](https://its.cern.ch/jira/browse/DMC-1427): Davix should always use the bundled RapidJson library

Over the long-term, the project should move away from depending on RapidJson.

Hope this time we can consider this issue closed.

Cheers,
Mihai
