### ISSUE TITLE
Allow forcing of bundled rapidjson

### ISSUE THREAD

**Issue by andresailer** [cern-fts/davix#125]
Dear Developers,

Would it be possible to add a cmake option to let us force the use of the bundled or external rapid json?

https://github.com/cern-fts/davix/blob/f41e619bb1079c7372af6e786c608ee6c3b9df02/CMakeLists.txt#L100

It would be unfortunate if we accidentally pick up one or the other depending on the build order of our software stacks (In my case building LCG software stacks).

Thanks!

**Comment by mpatrascoiu** [comment]
Hello Andre,

I think you are aware already by now, but I'll post here again the summary.

With the discussion that started in the ROOT project (https://github.com/root-project/root/issues/17190) and crossed-over to Davix (https://github.com/cern-fts/davix/issues/130), I went ahead and patched the Davix-bundled RapidJson library (thanks to https://github.com/cern-fts/davix/pull/129).

Since the latest officially released `rapidjson-devel-1.1.0` package does not have the fix, there's no other way but to use the bundle version at all times. The following commit does exactly that: [b4a53f12](https://github.com/cern-fts/davix/commit/b4a53f12)

This is documented and tracked further here: [DMC-1426](https://its.cern.ch/jira/browse/DMC-1426) / [DMC-1427](https://its.cern.ch/jira/browse/DMC-1427)

Over the long-term, the plan is to stop using RapidJson altogether, in favor of a more widely-supported library, such as `jsoncpp`.

Cheers,
Mihai

**Comment by andresailer** [comment]
Ok, no problem if you always use the bundled rapidjson.

**Comment by mpatrascoiu** [comment]
Hello again,

On a second thought (upon talking with @amadio ), I've decided to allow switching between the bundled/system RapidJSON library via the `EMBEDDED_RAPIDJSON=<True|False>` CMake variable (default True).

The corresponding JIRA issue ([DMC-1427](https://its.cern.ch/jira/browse/DMC-1427)) has been updated.

Cheers,
Mihai

**Comment by andresailer** [comment]
Still good for us :+1: :)

**Comment by mpatrascoiu** [comment]
Yes, you could use the default, bundled RapidJSON library in ROOT and be away from all this headache.

Over the (not-so)long-term, I plan to drop RapidJSON completely from Davix and switch to another JSON library, such as `jsoncpp` or maybe [nlohmann/json](https://github.com/nlohmann/json). (I think this is what ROOT uses, no?)

**Comment by mpatrascoiu** [comment]
Yes, I mean when compiling ROOT, you can use the Davix-bundled RapidJSON to compile the ROOT-bundled Davix :slightly_smiling_face: 

But my second question was general: which JSON library does ROOT use?

Cheers,
Mihai

**Comment by andresailer** [comment]
No, no, no I don't want to use rapidjson from ROOT to build Davix, and then use Davix inside ROOT. We want to have Davix stand alone for some reason. We also might want to not use the Davix version that comes along with Root.

Yes, ROOT does use nlohman json, I don't know if they use another one as well.

**Comment by amadio** [comment]
If you would like to use a library that is always external, while allowing ROOT to build Davix as builtin, you can try nlohmann_json. See [here](https://github.com/root-project/root/tree/master/builtins) the software that ROOT has bundled to avoid taking from the system when necessary. Cheers,

**Comment by mpatrascoiu** [comment]
Hello,
@andresailer what I meant: Davix now allows you to choose (via CMake) whether to use the system RapidJSON or the bundled RapidJSON within Davix. There's no RapidJSON dependency that Davix would need in the ROOT layer.

@amadio I see that [nlohmann-json](https://src.fedoraproject.org/rpms/json) is up-to-date in EPEL. I plan to switch Davix to this package (if it's easy to use). My goal is to remove the bundled dependencies and use only system ones
